FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/fastAPI.py .
COPY scripts/ ./scripts/
# (If you have model .pkl or .pt files, also add:)
# COPY *.pkl ./
# COPY *.pt ./

CMD ["uvicorn", "fastAPI:app", "--host", "0.0.0.0", "--port", "8080"]
